### PR TITLE
Add private key as an output

### PR DESCRIPTION
**Pull request by ekristen**
## what
* Add output for private key pem

## why
* There are times when you need the private key to be programmatically accessible

### CODE REVIEW

**Comment by Nuru** [comment]
@ekristen Thank you for the submission.

Unfortunately, exporting the private key as an output would cause it to be stored unencrypted in the Terraform state, which is a significant security problem. Even if it were stored encrypted, it would still make it programmatically accessible (which is your intent) without sufficient access controls to be considered secure. For that reason, I am closing this PR as unacceptable.

If you want to create an SSH Key Pair with programmatic access, you can use the Terraform resource directly

```hcl
resource "tls_private_key" "default" {      
  algorithm = var.ssh_key_algorithm
}
```

or you can use the fork you have already created.

**Comment by Nuru** [comment]
@ekristen My apologies, you are right, I am/was wrong. I will reopen the PR.
> The fact that the private key is managed as a terraform resource means that the private key is already in the terraform state file unencrypted. Simply adding it as an output means it'll be in two places in the terraform state instead of one.
> 

Please make the following changes:

- Add a boolean variable `private_key_output_enabled` defaulted to `false`
- When `private_key_output_enabled` is `false`, set the `private_key` output to `null`.

**Comment by ekristen** [comment]
@Nuru It's all good. Thank you for re-opening this. Requested changes have been made.

**Comment by SweetOps** [comment]
> Please make the following changes:
>
> Add a boolean variable private_key_output_enabled defaulted to false
>When private_key_output_enabled is false, set the private_key output to null.

@Nuru Why just not make it `sensitive` as it already done in  https://github.com/cloudposse/terraform-aws-key-pair/blob/master/outputs.tf#L16 ?

**Comment by Nuru** [comment]
/test all

@SweetOps wrote
> Why just not make it `sensitive` as it already done in https://github.com/cloudposse/terraform-aws-key-pair/blob/master/outputs.tf#L16 ?

Just making it sensitive will still put it in the output state where other Terraform modules can easily access it via remote state. Because of the security implications, that is a change that I do not want to happen automatically when users upgrade to the latest version of this module.

**Comment by Nuru** [comment]
@ekristen Sorry, not your fault, but this module is a bit out of date. Please run the following commands from the repo root:

```
make init
make github/init
```
and check in and push the changes

**Review by Nuru — APPROVED** [review]

**Pull request merged**
